### ISSUE TITLE
需求 | 希望添加一个娶指定群友的功能

### ISSUE THREAD

**Issue by qjksxy** [KarisAya/nonebot_plugin_groupmate_waifu#1]
比如在群里发送：娶@某人
然后有概率成功或者失败
以及可以查看当前都有哪些配对
同时这些情况最好也能处理一下：
1. A娶B成功，A再娶C
2. A娶B成功，C再娶B
3. A娶B成功，B再娶C
4. A娶B成功，C再娶A

感谢大大！

**Comment by KarisAya** [comment]
1、Nice Idea！
2、玩挺大.jpg
1. A娶B成功，A再娶C（你已经有老婆了！）
2. A娶B成功，C再娶B（B已经名花有主了）
3. A娶B成功，B再娶C（你是A的老婆！）
4. A娶B成功，C再娶A（击剑？！）

我打算返回类似上面提示消息，还有指定群友失败后单身一天。

**Comment by qjksxy** [comment]
好耶！期待大大

**Comment by KarisAya** [comment]
已更新1.1.0，更新内容在readme
