### ISSUE TITLE
涩涩记录指令报错

### ISSUE THREAD

**Issue by YTheSeven** [KarisAya/nonebot_plugin_groupmate_waifu#13]
![image](https://user-images.githubusercontent.com/49430862/217880465-71830bb1-7460-4260-a38c-241a64a4a805.png)
如图...

**Comment by KarisAya** [comment]
看起来是适配器的问题，更新一下OneBot V11 协议试试

**Comment by YTheSeven** [comment]
> 

我用的不是onebot耶，用的yunzai的python插件，看着我是搞不定了😖
