### ISSUE TITLE
娶群友10几次一直娶不到

### ISSUE THREAD

**Issue by CaffuChin0** [KarisAya/nonebot_plugin_groupmate_waifu#15]
疑似是被离婚的人无法另外娶群友
本群cp和群友卡池也没有这几个被离婚的人
请问一下怎么解决？
![0](https://user-images.githubusercontent.com/47897127/225798273-826916d9-c911-4f93-b8cc-457fb1decae1.png)
![1](https://user-images.githubusercontent.com/47897127/225798275-51079e9a-d668-4962-910c-fd4d8515bb4a.png)

**Comment by KarisAya** [comment]
娶群友是纯爱版，第一次就固定了。所以今天娶不到就只能等刷新了。
离婚是删除cp记录，离婚之后两个人都可以娶群友，不存在离婚无法娶群友的问题。

**Comment by KarisAya** [comment]
可以看一下插件保存的文件（如果配置了保存文件的话）
娶不到群友的群友实际上是在cp记录里的（所以排除出卡池），但是他娶到的是自己。

**Comment by CaffuChin0** [comment]
好的，谢谢您的解答，刚刚试了一下把record文件删了就没问题了，应该就是您说的这个。
