### ISSUE TITLE
透群友能否加个次数限制，群友们变成只会整天刷屏的打桩机了（悲

### ISSUE THREAD

**Issue by Kiana1314** [KarisAya/nonebot_plugin_groupmate_waifu#2]

**Comment by KarisAya** [comment]
不打算在这个插件上加次数限制，不过这个问题有解决方法。

**Comment by KarisAya** [comment]
我写了一个通用指令阻断插件，功能还不完善可以先凑合用。

**Comment by MoKeNeng** [comment]
可以不写次数限制，能不能写个透和娶的CD，他们一直发QAQ，电脑都要烂掉了

**Comment by KarisAya** [comment]
通用指令阻断可以设置cd

**Comment by MoKeNeng** [comment]
额。。能不能说明一下具体是那一段代码

**Comment by KarisAya** [comment]
https://github.com/KarisAya/nonebot_plugin_matcher_block
添加了readme

**Comment by MoKeNeng** [comment]
不好意思,还是不太懂。我现在想就是透了一次的cd30秒这样

**Comment by KarisAya** [comment]
安装 nonebot_plugin_matcher_block，然后在群里发送
添加阻断 透群友 冷却 30

**Comment by MoKeNeng** [comment]
懂了，刚刚看错插件了！！谢谢大佬
