### ISSUE TITLE
【功能建议】使用pil-utils

### ISSUE THREAD

**Issue by Sevenyine** [KarisAya/nonebot_plugin_groupmate_waifu#22]
[nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils)根据作者注明将会在一段时间内停止使用，可采用同作者替代品 [pil-utils](https://github.com/MeetWq/pil-utils)
和其他插件同依赖，减去部分配置时间

**Comment by KarisAya** [comment]
现在这个游戏插件的图片部分只有很少部分依赖[nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils)了，因为排版的需要实际上手搓图片转文字更合适。我会在未来的更新中（try）完全移除对这个插件的依赖。

**Comment by KarisAya** [comment]
看错插件了（

**Comment by KarisAya** [comment]
> 现在这个游戏插件的图片部分只有很少部分依赖[nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils)了，因为排版的需要实际上手搓图片转文字更合适。我会在未来的更新中（try）完全移除对这个插件的依赖。

还以为是[nonebot_plugin_game_collection](https://github.com/KarisAya/nonebot_plugin_game_collection)
