### ISSUE TITLE
报错：字典对象没有add方法

### ISSUE THREAD

**Issue by X-Skirt-X** [KarisAya/nonebot_plugin_groupmate_waifu#26]
如图：
![image](https://github.com/KarisAya/nonebot_plugin_groupmate_waifu/assets/91937041/9760c501-eb5b-47b6-9973-004b6cf821a6)

Python版本为3.8
我不知道是不是python版本的问题
系统环境为Ubuntu，Linux版本：Linux 5.10.110
Arm架构

----------------------------------------
小声bb：没看懂为什么会变成字典，前面不是
https://github.com/KarisAya/nonebot_plugin_groupmate_waifu/blob/bf08bc8866b7e813b7786953a7e073995e46ad53/__init__.py#L316-L318
了嘛

**Comment by KarisAya** [comment]
是不是加载了以前的记录？新版不兼容老存档
以前cp记录存在record_waifu这个文件里
现在cp记录存在record_CP文件里，record_waifu变成了被娶人的集合

**Comment by X-Skirt-X** [comment]
> 是不是加载了以前的记录？新版不兼容老存档 以前cp记录存在record_waifu这个文件里 现在cp记录存在record_CP文件里，record_waifu变成了被娶人的集合

记录保存在哪里啊（

**Comment by KarisAya** [comment]
bot根目录/data/waifu

**Comment by X-Skirt-X** [comment]
解决了，感谢
