### ISSUE TITLE
【使用】分手无回复信息

### ISSUE THREAD

**Issue by Z735803792** [KarisAya/nonebot_plugin_groupmate_waifu#5]
python3.9.15,ubuntu20.04
其他指令都正常，只有分手/离婚没有回复信息（有时候有用有时候没用，但无论如何都没有回复信息）

**Comment by KarisAya** [comment]
分手指令在没有娶到群友或没有娶群友的时候是不触发的，
然后分手有概率回复戳一戳。

**Comment by Z735803792** [comment]
分手后，但是本群cp记录是保留的，这个是bug还是本来就是这么设计的

**Comment by KarisAya** [comment]
分手后应该删除cp信息才对。
