### ISSUE TITLE
机器人每次重启，本群cp的记录就清零重置了，怎么设置不重置

### ISSUE THREAD

**Issue by AirKeen76** [KarisAya/nonebot_plugin_groupmate_waifu#7]
机器人每次重启，本群cp的记录就清零重置了，怎么设置不重置清零呢

**Comment by KarisAya** [comment]
cp列表是记录在内存里的，没有写成文件。关掉进程就自动清空了。

**Comment by MoKeNeng** [comment]
emm能不能搞个文本或者数据库啥的存一下

**Comment by MoKeNeng** [comment]
想保存下来

**Comment by KarisAya** [comment]
> 嗯嗯，知道啦 谢谢捏

更新到最新版本然后把配置第二条改成true
https://github.com/KarisAya/nonebot_plugin_groupmate_waifu#%E9%85%8D%E7%BD%AE
