### ISSUE TITLE
启动报错：能否兼容nonebot_plugin_apscheduler0.2.0版本

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [KarisAya/nonebot_plugin_groupmate_waifu#9]
![image](https://user-images.githubusercontent.com/70925546/206382442-48e8d1b1-0caf-4129-bd0f-6a6233013cb5.png)

**Comment by Z735803792** [comment]
刚刚看了下似乎是定时插件的问题，之前也一直用的0.1.4版本。现在大多插件都需要0.2.0版本了，希望可以适配下谢谢~

**Comment by KarisAya** [comment]
定时插件0.2.0不兼容nonebot2.0.0b5和这个插件有什么关系

**Comment by KarisAya** [comment]
这个插件在0.1.4和0.2.0都可以正常运行，这个报错是定时插件和nb之间的不兼容。

**Comment by Ikaros-521** [comment]
nonebot2  =  2.0.0b5
nonebot-plugin-groupmate-waifu  = 1.2.2.post0
nonebot-plugin-apscheduler    =   0.2.0

改`__init__.py`中的`scheduler = require("nonebot_plugin_apscheduler").scheduler`为
```
require("nonebot_plugin_apscheduler")
from nonebot_plugin_apscheduler import scheduler
```
